export const REVIEWS = [
  {
    id: 1,
    name: 'Aminata Diallo',
    role: 'Entrepreneur, Dakar',
    rating: 5,
    text: 'The Nova S25 Ultra changed how I run my business. The camera quality is unreal and the battery lasts my full working day without breaking a sweat.',
    avatar: 'AD',
    avatarColor: '#7c3aed',
    product: 'Nova S25 Ultra',
  },
  {
    id: 2,
    name: 'Kofi Mensah',
    role: 'Software Developer, Accra',
    rating: 5,
    text: 'Ordered on a Tuesday, arrived Wednesday morning. The NovaTab Pro is incredibly fast and the display is gorgeous for both coding and watching films.',
    avatar: 'KM',
    avatarColor: '#059669',
    product: 'NovaTab Pro 12',
  },
  {
    id: 3,
    name: 'Fatima El-Amin',
    role: 'Medical Doctor, Lagos',
    rating: 5,
    text: 'Paying with MTN MoMo was seamless. No issues, instant confirmation. The NovaCrystal TV arrived well packed and setup was a breeze.',
    avatar: 'FE',
    avatarColor: '#ea580c',
    product: 'NovaCrystal 65"',
  },
  {
    id: 4,
    name: 'Jean-Paul Nkosi',
    role: 'Journalist, Kinshasa',
    rating: 5,
    text: "The local French support team helped me set up everything in minutes. It's rare to get this level of service for tech purchases in DRC.",
    avatar: 'JN',
    avatarColor: '#0891b2',
    product: 'Nova S25+',
  },
  {
    id: 5,
    name: 'Chisom Okafor',
    role: 'Content Creator, Enugu',
    rating: 5,
    text: 'The camera does exactly what they promise. I shot an entire brand campaign with just the S25 Ultra. Clients thought I used professional equipment.',
    avatar: 'CO',
    avatarColor: '#dc2626',
    product: 'Nova S25 Ultra',
  },
  {
    id: 6,
    name: 'Aïssatou Touré',
    role: 'Teacher, Abidjan',
    rating: 5,
    text: 'Student discount saved me a lot and the free buds were a bonus. The phone is beautiful and the battery easily lasts two days with my usage.',
    avatar: 'AT',
    avatarColor: '#1428a0',
    product: 'Nova A55',
  },
]